version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: 'Generate code frome proto files'
    cmds:
      - protoc --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative proto/auth/auth.proto proto/permissions/permissions.proto
