name: Generate Proto

on:
  push:
    paths:
      - 'proto/**/*.proto'
  pull_request:
    paths:
      - 'proto/**/*.proto'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '25.2' # или другая нужная версия

      - name: Install Go plugins for protoc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Generate proto code
        run: task gen

      # (опционально) Проверка, что код сгенерирован и всё в гите
      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ Есть несохранённые изменения после генерации. Закоммить их!" && exit 1
          else
            echo "✅ Всё чисто."
          fi
